apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - namespace-maas-infra.yaml
  - maas-postgres.yaml
  - maas-db-secret.yaml
  - kuadrant-crds.yaml
  - maas-auth-proxy.yaml
  - fix-gateway-auth-policy.yaml

patches:
  - path: patch-datasciencecluster.yaml
    target:
      kind: DataScienceCluster
