---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: maas-db-config
  namespace: redhat-ai-gateway-infra
spec:
  encryptedData:
    DB_CONNECTION_URL: AgBcS+djD8xEz9lV/mMIUvrNmAq/oP/4i8eaZpUV+5LGsJLXbsj8i/0fglvnL1XFcj+UWfAykDedQnAqBlE4QVtQAcYlXcHqI2YE3WgwdQrd5oigkBHdYJtHwsScwDybYUHUvpEUa114jWwuqnidzfg1Pj40dg+Mw1XOQZJCrZnG3B+9FQF77JP39saGDmtfHSbTdlDu3E8G0taFMfCEBD7GehQSpXvn0BAWSqRNWh+IkKW/3AERwp5y+aFxbK516jm/IGV6vBHXjbnnA1VK1UMKP77hxwf4ybqQo2YDX2fKZShHAlQHUKO9NfrqlxYE+GZrMsuTuI7iDyqylCjBFkoiLZ5Dcil06d0TsCgY+2/knIAteWiJUA4DdPlaqnt1xrnPBjDMxlBaBQGTAkRzXzoO9Wr4Yzxdhp5Xvg/Q5TaE9LqigfgiVghp4eA0yEQEicG+5vf/sEl+9uCvWhM8czH6KdTwyXxnK6m56Znmjo3UkYu/usgX0Hve1vRm8el5ej3BOo/3hSCY3rrHOLSPI6Tu5gcLBQcfSTJWXwocZmNO2mi9+POwHvrP5wZ7EIYMlpQV9xJYxgkC2LirOq6g5zCwOvlRZ52SwF/7SqK1zq8Wo1vJMT8AomrpTM7TRqWG3ndYo/y9a1sQdQKdeuxDiZoGpIlZYxD4KnTsydL7jp+Hc7UitRU1l5PTgkQQWtJX/YtrDCKa6hfZ7lco/xMjg/LyZr8EBfRrG97TbS+8WWBe6pNEH0iTxrMqTXnqWKzGfiV+qoZT30os6WyCrhyQLTdEOjsfOkXOx69abmIrf6xBTWvRyMsdPg1kj6HijojEW6x2HGE=
  template:
    metadata:
      name: maas-db-config
      namespace: redhat-ai-gateway-infra
      labels:
        app.kubernetes.io/part-of: modelops
    type: Opaque
