apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
type: Opaque
stringData:
  DB_CONNECTION_URL: "postgresql://maas:maas-sandbox-password@maas-postgres.maas-infra.svc.cluster.local:5432/maas"
