apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhoai-model-registries

resources:
  - ../../../model_onboarding_pipeline/model-registry/mysql-secret.yaml
  - ../../../model_onboarding_pipeline/model-registry/mysql-pvc.yaml
  - ../../../model_onboarding_pipeline/model-registry/mysql-deployment.yaml
  - ../../../model_onboarding_pipeline/model-registry/mysql-service.yaml
  - ../../../model_onboarding_pipeline/model-registry/modelregistry-instance.yaml
