apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/sandbox-pipeline.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/promotion-pipeline.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/deploy-model-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/deploy-maas-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/security-scan-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/compliance-artifact-scan-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/guidellm-benchmark-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/approval-gate-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/gpu-advisor-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/gpu-advisor-promotion-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/apply-gpu-sharing-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/grant-model-access-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/model-registry-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/promote-and-benchmark-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/teardown-model-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/lm-eval-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/upload-guidellm-results-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/upload-lm-eval-results-task.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/pvc.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/gpu-sharing-rbac.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/gpu-advisor-credentials-secret.yaml
  - ../../../model_onboarding_pipeline/model-intake-pipeline/pipeline/mmlu.yaml
