//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkTargets) DeepCopyInto(out *BenchmarkTargets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkTargets.
func (in *BenchmarkTargets) DeepCopy() *BenchmarkTargets {
	if in == nil {
		return nil
	}
	out := new(BenchmarkTargets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlan) DeepCopyInto(out *CapacityPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlan.
func (in *CapacityPlan) DeepCopy() *CapacityPlan {
	if in == nil {
		return nil
	}
	out := new(CapacityPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanList) DeepCopyInto(out *CapacityPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapacityPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanList.
func (in *CapacityPlanList) DeepCopy() *CapacityPlanList {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanModelRef) DeepCopyInto(out *CapacityPlanModelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanModelRef.
func (in *CapacityPlanModelRef) DeepCopy() *CapacityPlanModelRef {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanModelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanSpec) DeepCopyInto(out *CapacityPlanSpec) {
	*out = *in
	out.ModelRef = in.ModelRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanSpec.
func (in *CapacityPlanSpec) DeepCopy() *CapacityPlanSpec {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanStatus) DeepCopyInto(out *CapacityPlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanStatus.
func (in *CapacityPlanStatus) DeepCopy() *CapacityPlanStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUConfig) DeepCopyInto(out *GPUConfig) {
	*out = *in
	if in.AllowTimeSlicing != nil {
		in, out := &in.AllowTimeSlicing, &out.AllowTimeSlicing
		*out = new(bool)
		**out = **in
	}
	if in.AllowMIG != nil {
		in, out := &in.AllowMIG, &out.AllowMIG
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUConfig.
func (in *GPUConfig) DeepCopy() *GPUConfig {
	if in == nil {
		return nil
	}
	out := new(GPUConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntakeProviderConfig) DeepCopyInto(out *IntakeProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntakeProviderConfig.
func (in *IntakeProviderConfig) DeepCopy() *IntakeProviderConfig {
	if in == nil {
		return nil
	}
	out := new(IntakeProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntakeProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntakeProviderConfigList) DeepCopyInto(out *IntakeProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IntakeProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntakeProviderConfigList.
func (in *IntakeProviderConfigList) DeepCopy() *IntakeProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(IntakeProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntakeProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntakeProviderConfigSpec) DeepCopyInto(out *IntakeProviderConfigSpec) {
	*out = *in
	if in.PipelineTimeout != nil {
		in, out := &in.PipelineTimeout, &out.PipelineTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Workspaces != nil {
		in, out := &in.Workspaces, &out.Workspaces
		*out = make([]IntakeProviderWorkspace, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntakeProviderConfigSpec.
func (in *IntakeProviderConfigSpec) DeepCopy() *IntakeProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IntakeProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntakeProviderConfigStatus) DeepCopyInto(out *IntakeProviderConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntakeProviderConfigStatus.
func (in *IntakeProviderConfigStatus) DeepCopy() *IntakeProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(IntakeProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntakeProviderWorkspace) DeepCopyInto(out *IntakeProviderWorkspace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntakeProviderWorkspace.
func (in *IntakeProviderWorkspace) DeepCopy() *IntakeProviderWorkspace {
	if in == nil {
		return nil
	}
	out := new(IntakeProviderWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaaSOverride) DeepCopyInto(out *MaaSOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaaSOverride.
func (in *MaaSOverride) DeepCopy() *MaaSOverride {
	if in == nil {
		return nil
	}
	out := new(MaaSOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelAccess) DeepCopyInto(out *ModelAccess) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelAccess.
func (in *ModelAccess) DeepCopy() *ModelAccess {
	if in == nil {
		return nil
	}
	out := new(ModelAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelIdentity) DeepCopyInto(out *ModelIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelIdentity.
func (in *ModelIdentity) DeepCopy() *ModelIdentity {
	if in == nil {
		return nil
	}
	out := new(ModelIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLifecycleProfile) DeepCopyInto(out *ModelLifecycleProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLifecycleProfile.
func (in *ModelLifecycleProfile) DeepCopy() *ModelLifecycleProfile {
	if in == nil {
		return nil
	}
	out := new(ModelLifecycleProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelLifecycleProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLifecycleProfileList) DeepCopyInto(out *ModelLifecycleProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelLifecycleProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLifecycleProfileList.
func (in *ModelLifecycleProfileList) DeepCopy() *ModelLifecycleProfileList {
	if in == nil {
		return nil
	}
	out := new(ModelLifecycleProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelLifecycleProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLifecycleProfileSpec) DeepCopyInto(out *ModelLifecycleProfileSpec) {
	*out = *in
	out.Workflow = in.Workflow
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(ProviderConfigRef)
		**out = **in
	}
	if in.DefaultAccess != nil {
		in, out := &in.DefaultAccess, &out.DefaultAccess
		*out = new(ModelAccess)
		**out = **in
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]ProfileStageSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLifecycleProfileSpec.
func (in *ModelLifecycleProfileSpec) DeepCopy() *ModelLifecycleProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ModelLifecycleProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLifecycleProfileStatus) DeepCopyInto(out *ModelLifecycleProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLifecycleProfileStatus.
func (in *ModelLifecycleProfileStatus) DeepCopy() *ModelLifecycleProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ModelLifecycleProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRequest) DeepCopyInto(out *ModelRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRequest.
func (in *ModelRequest) DeepCopy() *ModelRequest {
	if in == nil {
		return nil
	}
	out := new(ModelRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRequestList) DeepCopyInto(out *ModelRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRequestList.
func (in *ModelRequestList) DeepCopy() *ModelRequestList {
	if in == nil {
		return nil
	}
	out := new(ModelRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRequestSpec) DeepCopyInto(out *ModelRequestSpec) {
	*out = *in
	out.Model = in.Model
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(ModelRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = new(ModelAccess)
		**out = **in
	}
	if in.MaaS != nil {
		in, out := &in.MaaS, &out.MaaS
		*out = new(MaaSOverride)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRequestSpec.
func (in *ModelRequestSpec) DeepCopy() *ModelRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRequestStatus) DeepCopyInto(out *ModelRequestStatus) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]StageProgress, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRequestStatus.
func (in *ModelRequestStatus) DeepCopy() *ModelRequestStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRequirements) DeepCopyInto(out *ModelRequirements) {
	*out = *in
	in.GPUConfig.DeepCopyInto(&out.GPUConfig)
	out.BenchmarkTargets = in.BenchmarkTargets
	out.SecurityConfig = in.SecurityConfig
	out.DeploymentConfig = in.DeploymentConfig
	if in.PromotionNamespaces != nil {
		in, out := &in.PromotionNamespaces, &out.PromotionNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRequirements.
func (in *ModelRequirements) DeepCopy() *ModelRequirements {
	if in == nil {
		return nil
	}
	out := new(ModelRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformConfig) DeepCopyInto(out *PlatformConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformConfig.
func (in *PlatformConfig) DeepCopy() *PlatformConfig {
	if in == nil {
		return nil
	}
	out := new(PlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformConfigList) DeepCopyInto(out *PlatformConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformConfigList.
func (in *PlatformConfigList) DeepCopy() *PlatformConfigList {
	if in == nil {
		return nil
	}
	out := new(PlatformConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformConfigSpec) DeepCopyInto(out *PlatformConfigSpec) {
	*out = *in
	if in.ComplianceAllowedArch != nil {
		in, out := &in.ComplianceAllowedArch, &out.ComplianceAllowedArch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformConfigSpec.
func (in *PlatformConfigSpec) DeepCopy() *PlatformConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformConfigStatus) DeepCopyInto(out *PlatformConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformConfigStatus.
func (in *PlatformConfigStatus) DeepCopy() *PlatformConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileStageSpec) DeepCopyInto(out *ProfileStageSpec) {
	*out = *in
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(ProviderConfigRef)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.NamespaceSetup != nil {
		in, out := &in.NamespaceSetup, &out.NamespaceSetup
		*out = new(StageNamespaceSetup)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileStageSpec.
func (in *ProfileStageSpec) DeepCopy() *ProfileStageSpec {
	if in == nil {
		return nil
	}
	out := new(ProfileStageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigRef) DeepCopyInto(out *ProviderConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigRef.
func (in *ProviderConfigRef) DeepCopy() *ProviderConfigRef {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	if in.Backoff != nil {
		in, out := &in.Backoff, &out.Backoff
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageNamespaceSetup) DeepCopyInto(out *StageNamespaceSetup) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AllowedNamespaceSelector != nil {
		in, out := &in.AllowedNamespaceSelector, &out.AllowedNamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageNamespaceSetup.
func (in *StageNamespaceSetup) DeepCopy() *StageNamespaceSetup {
	if in == nil {
		return nil
	}
	out := new(StageNamespaceSetup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageProgress) DeepCopyInto(out *StageProgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageProgress.
func (in *StageProgress) DeepCopy() *StageProgress {
	if in == nil {
		return nil
	}
	out := new(StageProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookProviderConfig) DeepCopyInto(out *WebhookProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookProviderConfig.
func (in *WebhookProviderConfig) DeepCopy() *WebhookProviderConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookProviderConfigList) DeepCopyInto(out *WebhookProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookProviderConfigList.
func (in *WebhookProviderConfigList) DeepCopy() *WebhookProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(WebhookProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookProviderConfigSpec) DeepCopyInto(out *WebhookProviderConfigSpec) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AuthHeaderPrefix != nil {
		in, out := &in.AuthHeaderPrefix, &out.AuthHeaderPrefix
		*out = new(string)
		**out = **in
	}
	in.StatusMapping.DeepCopyInto(&out.StatusMapping)
	if in.SubmitTimeout != nil {
		in, out := &in.SubmitTimeout, &out.SubmitTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PollTimeout != nil {
		in, out := &in.PollTimeout, &out.PollTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SubmitRetry != nil {
		in, out := &in.SubmitRetry, &out.SubmitRetry
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.PollRetry != nil {
		in, out := &in.PollRetry, &out.PollRetry
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookProviderConfigSpec.
func (in *WebhookProviderConfigSpec) DeepCopy() *WebhookProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookProviderConfigStatus) DeepCopyInto(out *WebhookProviderConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookProviderConfigStatus.
func (in *WebhookProviderConfigStatus) DeepCopy() *WebhookProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookStatusMapping) DeepCopyInto(out *WebhookStatusMapping) {
	*out = *in
	if in.PhaseValueMap != nil {
		in, out := &in.PhaseValueMap, &out.PhaseValueMap
		*out = make(map[string]StagePhase, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookStatusMapping.
func (in *WebhookStatusMapping) DeepCopy() *WebhookStatusMapping {
	if in == nil {
		return nil
	}
	out := new(WebhookStatusMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowRef) DeepCopyInto(out *WorkflowRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowRef.
func (in *WorkflowRef) DeepCopy() *WorkflowRef {
	if in == nil {
		return nil
	}
	out := new(WorkflowRef)
	in.DeepCopyInto(out)
	return out
}
