apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-inference
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: modelops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: modelops
  source:
    repoURL: https://github.com/jhurlocker/ModelOps.git
    targetRevision: feat/model-request-controller
    path: gitops/components/model-inference
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "5m"
