apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modelops-pipelines
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: modelops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: modelops
  source:
    repoURL: https://github.com/jhurlocker/ModelOps.git
    targetRevision: feat/model-request-controller
    path: model_onboarding_pipeline/model-intake-pipeline/pipeline
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "5m"
