apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modelops-storage

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

secretGenerator:
  - name: minio-credentials
    literals:
      - root-user=minioadmin
      - root-password=minioadmin
