---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: modelops-storage
spec:
  encryptedData:
    root-password: AgCarYET6X8s5nn4+1oHTBluXZk2uPNQrOz80Y6MU8EadqlBkyXx8jIQNdp0xMIuCD0SR5XGYP6WiIc4YdPviM/7bLQNLoFEZibxx/md+O3e04AAm+Lz1uSWgGQKpMfstrsI3/2aOF5iD6l22NHhr9/rbxDYs/umPMCiUi1uQegd6+O/SsnjHwK4+YwCPERmC6oe3YJLhlnUQN15inMFQ0EwpDUf7a03fX+HDROLVZjmsa/9wleUiCGfYP4dpytUd0uqfyAwF6J/cP7m3+noH/oA1x6JsxLYorzrsykF+FEcGHzpGp4vb4VFVuQMQRjB6olO25y1v/rZTLUMiz33ab22fV628VDmc9V3ExRn9+DVzievEm31tc5LwWXgeyAkoAtciFYYgdjpbYUdJhOrVnyv3wzybu++Z8kS0PdOsKVwlja/7Yt3WBVMhKHEi7KJhafh394X/8J/hJpg2BeRYIDMmeDXZB3ar0sngU521FJS6uhFWBl0KuvfviuJ6MzksoXrehoa2f5rHEAgcT6clYTEMil16ZSQEQTOAu9Cvd46k8BQuBy+3+f4Rse3NwWvxizKoqaInxgz9h0btZZWkrmUiTlIMd67m8LaV5aVV1Os49CnF3st7q0pLiU7CPW7kjo2OVfrPQ/lsFdJRXrnibTODjqc4GTVZTRbxOsat2SVGEDkqYDdHupvDbG3qi8/7WD9nu12lp2wBnNekxSzBymcrBEpeLm62HfqRAPk
    root-user: AgB4muuy6FIYx94EozNxqbtCYDqp4aC8YCX8QFdJ6uyjh1Bv0c3CsFkhHgJl2KNxyEUlIJxUezTatxZe8kIKTbvE7QsOeW+mP2B0EHVWllsjrhHTEnmfEluNFg3ApVjkJJ5m6jBJ6MtH5UgtL0jHVXpff+wqEKrx+CowyBEGkrTh8KvSiKZFRB20XErCatWPIvn3DKQNH7twTG9tDOUkaPTyuf/TgEHuQRXlzyyPq8A2xhHXNDGqVWY650OSl3AfLQtfQbRmmflIsKINEMaX8bZW7cFXtX87RXrPNXFciJj8YryqV490vJ0p+uVDxqamT/ydC/3mVgk9EtxQWSR5sx/OEWyTbk9yuyYGRHIKqe1pdXDjm9LkCZ8teIso0tmTq7+kUvlG1fdMVO7Wk9pwz5zMN4wof7RaPVFRZTboYpn7H+ueKhs0U4v/UsvXFUasKollzc+0JRNDi2un0i2mpONNtdHL/ETN/yEF0ttbZ1dYx9qsFZUNHcur92xRi0g9uhPBfZNXYVm2JW2Y7WxfWwQpo2CbzlbJL8me7IGN60Iijau8NezrzVq1gDsCxlEtQ9msBgBAYhUSEVVou+33YIt/0HunRDa9NcHptx8kPEwtzqmDxStZzBdJS2t4jvk9bQkAxhsSiJkv9z/16wvZ0mN0xS4/G6tx1OiNOV265xrXLhqpW4j+GFw8Xfx35h3qJTuevF8QO+MfcZWnVCpru01HWEQ/10A9DuIh
  template:
    metadata:
      name: minio-credentials
      namespace: modelops-storage
      labels:
        app.kubernetes.io/part-of: modelops
    type: Opaque
