---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: model-intake-secrets
  namespace: sandbox
spec:
  encryptedData:
    DEFAULT_S3_ACCESS_KEY: AgCzkdKnk46wSbNXZoy69MLBgkspBtuDko6Wa/IfE6CkJ0lMAunhSe7KKidN9lVQZjxnl7w/PL5BtsyFaqDI/AVSl8wzCqubHkmj6xBnc8d6Ff5poUMTMNtki2zD8yeliRCCIU5nAElqVk81a6DQhOzEEPlX9DnRJJ9IsPclQO1aff+4gqUs1tTeNFqnPyqs1MMOIswDSwy+CuVjI3p2skf5EoEjn+6kTtpSgy8NnbCUwrYMpPjpCN9jsYihvfwk2l9HQbb1fo56XoNowArgiB4xuEs15BBHTbLkTa0BW+8W8GZIrU+jGSxkl8++W1Sr/t5i7gL1HTFVoUqAYQZYXgnSA41yf60pYSHmN1x/NI9KK9mp9voMzGg4Hn9GVU4sA+VzNfgaIqSFmnbfltsuCRSiHHCv83hUzcm1DIieLPQfeBO48u68mRx8QuCllPfRBDsbghqnBQV4bSmruOaSttmkhXz55AfVjNpjv/I9rgQ77gDX/8cQbm7hHOGCxmvLGSNooSTZpMN4+8D+mi172G4c9Gf8wKIw/IvtqqsZE9hnBUibqmJBZWrZx5aWz+8Gq6DH3LVDlht3bOauLPJSdxDfVnMzVtUS0uXqqbkPm81IOKF/9GNIBNG5OUrNor0GLumwTMZLwIkodj/gdVbhlr7A27d/CfJkbREAzqbEQ23PMC8drNMoAI9TwYvfx3mxP25yTBYid/jT4d/r3KZ2vHa+wT8SQb1uvfBx
    DEFAULT_S3_SECRET_KEY: AgCX55bpXg2cCZXh893xHUdlUK2kmoc8lKQ+D+80joiIMu1N5NG8i8e64CfGqAwckCYSls8rh1/VlwkzEcQGPydxjp1ovsVDJ7CJn+vkj566h49Mb2QN3aLad1X1ONEDoxMtnTGbP8dHhRObsDC5L2qDUdB2V8KDzr8aLJdBF4/0G7ig7RAZKBlMTQwGsZ0N+evQ7NQpvDOt9iHBIue+F89H+RPnYC3krOEj5n0hAcIaHixPt/0faugaaLrGi7gOAIL9W8YD+HMQwUSYPoHHnOls2e0rkGRFbQ2BSPeoZ+7ykZ2K0i/+DcJ9x1GXkQUS55NKEeVreJb1xwdGXC8QMMUiT0dj4OTAFHzQcjWlusa1dX3/UYTaP/QdJBnycjbG7Fm939w0gn9bWb7KZ4ynk4XN5MCPZRvHj6XxOmdiQRMqzXe9tt0wL3OSnewCJ1oLd3TIg6tsirFvTMX5I4Wf8MaM7IAuW+6J1x6Z/DFSF36J0z6cBaXsfVxSUYLiDh/V6vsESx8MNEmLz7A5VBwxxomKjEFL5NeAZeqe3Pm+SsmJXzeHg5biw9jSun9l7Nr1OPnGeWzqHMamsziisCPksEkdzwkUgJBn2+s0/1XUbE9xRXt0vEq3yzPjTnDxZu7RAYscLIze3rFU1I6jvMbwd7SPjkk/8ruMHkr+7hLldSXcdhx8rsGEg3LnlFsj9TabOY4K2YiuLMVhnRK8zIu/+6NQq2TGkNS0UVHLGiro
  template:
    metadata:
      name: model-intake-secrets
      namespace: sandbox
      labels:
        app.kubernetes.io/part-of: modelops
    type: Opaque
