---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zot-htpasswd
  namespace: modelops-zot
spec:
  encryptedData:
    htpasswd: AgBnixUFwBdWvdVEInQundzqfwSgUzTQNqPe8xjG2P9hUdyjcnrO3ckr71yZR5XUmsJ/u+/esdNBKe/JzFN7FMEheQAVHHHGlrBKd+zb4y2WOwMmdjtErieit8Y6oRpRq6epFGgZ0T+KfVWL/ftH2ifM24IcZLvBVRq1OdPVZiSJK8hAgeYDukMQySeSRcpPnplP9UYmngbdwqIW54V+DirWgdrMcTIn7cmrQDMo1t3YqtMXRP6jR5zS38L2uLPfZLAwByhzESLi/fxS0EkpcNxGHohkNneLn7J94SnEyLSGh+gjKJ/s2QloKlQ/BPUMioCV2O4V2mJIz8lKsAFJ1NqYr2/RTzj6R3tEkakkpPlWFioECIui0vfBLcSqdRBYOe89w6MA0Qmb0d5QNoBiuJU3zQL9Dz1a0HCV8KzfrmfPEdHZdsoPFf8gKc9VGsD0CaIITup4paDMdpnTJZCWJlLc3I9dEFyeGU0eB+U87JWohpKsqAV/abMYWlXjc6rozx0koHZYHZoHK3CqCIWhCKVvhqdBaRCyP54S8bmZrkn/bLk/sFk/3eKvzwXyKp6EMBFVR6+3pBBOVBaqfgjaLcHlWSm+xAsaxr7ULKP8jaYl5upLaYXbzvbvTRzpF3I2s6VKd4TpJWP07hSec8+pSx+SqPOE8sYHHfApfW/xJ7SF9Iq/9cB3ODYK7kSxgX3Qq5K1lJRbvc1nQZkwitK8ebO8cx2faJJGezL5Lvquj/smn/OoL69Yvthv3MgMEnhaR5xoP7Ci7zDgfauoyDaVg3IwpZ9APP0=
  template:
    metadata:
      name: zot-htpasswd
      namespace: modelops-zot
      labels:
        app.kubernetes.io/part-of: modelops
    type: Opaque
