---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelops-operator-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - modelops.example.io
  resources:
  - capacityplans
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - modelops.example.io
  resources:
  - capacityplans/status
  - modelrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - modelops.example.io
  resources:
  - intakeproviderconfigs
  - modellifecycleprofiles
  - platformconfigs
  - webhookproviderconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - modelops.example.io
  resources:
  - modelrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - modelops.example.io
  resources:
  - modelrequests/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
