apiVersion: trustyai.opendatahub.io/v1alpha1
kind: EvalHub
metadata:
  name: default-evalhub
  namespace: redhat-ods-applications
spec:
  database:
    type: sqlite
  providers:
  - garak
  - garak-kfp
  - lm-evaluation-harness
  - guidellm
  collections:
  - leaderboard-v2
  - safety-and-fairness-v1
  - toxicity-and-ethical-principles
