apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: upload-guidellm-benchmark-results
spec:
  description: Upload guidellm benchmark results to s3 bucket
  params:
    - default: 'http://s3.openshift-storage.svc.cluster.local:80'
      description: s3 API endpoint
      name: s3-api-endpoint
      type: string
    - default: test
      description: s3 access key ID
      name: s3-access-key-id
      type: string
    - default: test
      description: s3 secret access key
      name: s3-secret-access-key
      type: string
  steps:
    - name: upload-benchmark
      image: quay.io/jhurlocker/s3-upload:latest
      workingDir: $(workspaces.shared-workspace.path)
      env:
        - name: S3_ENDPOINT_URL
          value: $(params.s3-api-endpoint)
        - name: S3_ACCESS_KEY_ID
          value: $(params.s3-access-key-id)
        - name: S3_SECRET_ACCESS_KEY
          value: $(params.s3-secret-access-key)
        - name: S3_BUCKET
          value: benchmark-results
        - name: TIMESTAMP
          value: $(cat timestamp.txt 2>/dev/null || echo "unknown")
        - name: PATTERN
          value: "*$(cat timestamp.txt 2>/dev/null)*"

  workspaces:
    - description: Shared workspace for storing benchmark results
      name: shared-workspace