FROM registry.access.redhat.com/ubi9/python-311:latest

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py /usr/local/bin/shim-app.py

ENV SHIM_AUTH_TOKEN=""

ENTRYPOINT ["python3", "/usr/local/bin/shim-app.py"]
