apiVersion: modelops.example.io/v1alpha1
kind: ModelLifecycleProfile
metadata:
  name: standard-generative-onboarding
  namespace: sandbox
spec:
  workflow:
    engine: tekton
    pipelineRef: model-intake-sandbox
  platformConfigRef: default-modelops-platform
  defaultAccess:
    authorizedViewers: ""
    accessRole: view
