FROM registry.access.redhat.com/ubi9/python-311:latest

RUN pip install --no-cache-dir boto3

COPY evaluate.py /usr/local/bin/compliance-scanner

ENTRYPOINT ["python3", "/usr/local/bin/compliance-scanner"]
