apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sandbox

resources:
  - platformconfig.yaml
  - lifecycleprofile.yaml
  - intakeproviderconfig.yaml
  - secrets.yaml
  - scan-s3-credentials-sealedsecret.yaml
  - result-s3-credentials-sealedsecret.yaml
  - zot-push-credentials-sealedsecret.yaml
  - zot-service-ca.yaml
