apiVersion: v1
kind: Secret
metadata:
  name: scan-s3-credentials
  namespace: sandbox
  labels:
    app.kubernetes.io/part-of: modelops
type: Opaque
data:
  accessKeyId: bWluaW9hZG1pbg==
  endpoint: aHR0cHM6Ly9taW5pby1tb2RlbG9wcy1zdG9yYWdlLmFwcHMub2NwLndwbXpwLnNhbmRib3gyODU1Lm9wZW50bGMuY29t
  secretAccessKey: bWluaW9hZG1pbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: result-s3-credentials
  namespace: sandbox
  labels:
    app.kubernetes.io/part-of: modelops
type: Opaque
data:
  accessKeyId: bWluaW9hZG1pbg==
  endpoint: aHR0cHM6Ly9taW5pby1tb2RlbG9wcy1zdG9yYWdlLmFwcHMub2NwLndwbXpwLnNhbmRib3gyODU1Lm9wZW50bGMuY29t
  secretAccessKey: bWluaW9hZG1pbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: evalhub-credentials
  namespace: sandbox
  labels:
    app.kubernetes.io/part-of: modelops
type: Opaque
data:
  url: aHR0cHM6Ly9taW5pby1tb2RlbG9wcy1zdG9yYWdlLmFwcHMub2NwLndwbXpwLnNhbmRib3gyODU1Lm9wZW50bGMuY29t
