---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zot-push-credentials
  namespace: sandbox
spec:
  encryptedData:
    password: AgDBm1tT+Bi23qmluoN2ZJaV4m6oWguT4VvBYsWkSMcuAUh1abRS4g8Wd5reHawp+fPPZ6zoSVUvrdD/c5igOhmiVM8PaTIGxYN9tlhraXUBrfUsu+WkW6GhUWrvuNAW8cktIHOyqxWXAEM9XSyoRj1pRyr4f2PjJOj8r1MPW947EY6nT7ulsRKsSS/rVhc9R5P+F4/j6+HAtVPIS3uC9bggnu2WvzJjWGM3hzP6iiX6352JacQywJBukyCqr+TBkEP6uKOJUHy7YL5wPT9ci3ZQjl+EGy7KByh9zxD/T91bNBS+SrF1MDyq6jyQd6ldLhVgFOk+ZRYoYNuXV/W8OwwqN6u/NGhZfzxh2FlFDecisVQrRCzhrfGAY9WoJG7Qh7tsBxrjOOxlqYHSBVuqe9q0uAMaNy3rXZqKAdwi3vwamMPobUIRD6GrGPrcux6JoMP5imkgi4szodwpvdkLRdbafEaKYc+G+XtxjMlMxVhWxvixp/yrLIfhqxTFChFYu4++vEPp6bFjntuS9S/3y1gz0hjIP7jlR9oyZbFXfFoGfzgFc8jg/bDXnemZUb3jSQggoadGTjjMKTTB2nU+kNBa0VdtqwbkhqOa1jXo2CUr2tIAdpwl0RCOI2d+SQ6Uyl8EsFHSZ221WPdQlf66gqVwqPraN/vkWwkue6qTE32e+6r1ZiUB4JiwL/Z4tsL6s5Ut5ajbw2t+cthni3jBprg/jDcroqrLIUpMvSbO
    username: AgB2k8oNsggWWHSVpd4GbGzydh6celqXhTKA2n6nLpuTpBzpT78ZwzeAcMnhYtYQAUdvpQ55WjejQ8c+okIF/M+lMyQs6yj/2xbuecjGzCYtsc9guI9nleJdJ+xV/hZRiRhbnUFCpeDCUT+GpvvGHl1YD+XgaWXWY4qrUTnqBJPJuacbcvyDKqgM5Z4VINs1Rg1upGcWnndK0IcUeFvMu5rkl0RDfzHS74OrS2GTcMWIjAhIB5WFzsMcvcilcXUhnJJL1PY4c8sIcNB9WW8uwQqGan0lvRmNzOs6vEo6uwKM+H3jbYATm4gdfjWcIbQglxrPxf9fU7aXJp2ub6m49uHjnOzZOtjCIbGBrmPHfbA/591jnC0/V2PQ9QPQRSPZzvnTV2mtG+G7ImYJoPybGW1jbLgt+jtCnuIGN61H51mp8X/G9DJIWeOPbEP7y5Pp2E/Nqm04DX5bo0WYOr5H6gZYOHiDUaKDtyqpgJmjVcLs9C604almnIwV6cZJ8Wzd1HLXfvtej5Yw4PZ7ZVMv/zcBG2qptVFO+Ji0X6q9HYx/nQu8KzLWu3YS4Yzs4z18irOJsQk2rmuJRDbuCWzKcZpQpSkVIOjCK9142cdv0LswAN3/72JL9+0N8hurtpDwgdIMNGCn2L/LNGvwU/3UeRGtG0z32u3/H5Bo111/kuAPD+ubPscQ71Xk1f43vz5hx/Gwr2h58lk97w==
  template:
    metadata:
      name: zot-push-credentials
      namespace: sandbox
      labels:
        app.kubernetes.io/part-of: modelops
    type: Opaque
